from fpdf import FPDF
from datetime import datetime
import os
import urllib.request
import tempfile

ICON_HEART_URL = "https://cdn-icons-png.flaticon.com/512/2966/2966486.png"

class PDFReport(FPDF):
    def header(self):
        # Logo (Right Aligned)
        try:
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp_logo:
                urllib.request.urlretrieve(ICON_HEART_URL, tmp_logo.name)
                self.image(tmp_logo.name, x=185, y=8, w=15)
        except:
            pass 

        # Title (Left Aligned)
        self.set_font('Arial', 'B', 20)
        self.set_text_color(52, 152, 219) # MedAI Blue
        self.cell(0, 10, 'MedAI-Cardiac', 0, 1, 'L')
        
        self.set_font('Arial', 'I', 10)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, 'Advanced AI Diagnostic System', 0, 1, 'L')
        
        self.ln(5)
        self.set_draw_color(200, 200, 200)
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by MedAI-Cardiac System | {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

    def section_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(44, 62, 80) # Dark Blue/Grey
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)

    def info_row(self, label, value):
        self.set_font('Arial', 'B', 10)
        self.set_text_color(0, 0, 0)
        self.cell(45, 6, label, 0, 0)
        self.set_font('Arial', '', 10)
        self.cell(0, 6, str(value), 0, 1)

def generate_pdf(patient_data, risk_score, bpm, hrv, fig_path, doctor_name):
    pdf = PDFReport()
    pdf.add_page()
    
    # --- 1. Patient & Doctor Information ---
    pdf.section_title("Examination Details")
    
    # Patient Block
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 8, "Patient Data:", 0, 1)
    pdf.info_row("Name:", f"{patient_data['first_name']} {patient_data['last_name']}")
    pdf.info_row("CNP:", patient_data['cnp'])
    pdf.info_row("Age / Sex:", f"{patient_data['age']} years / {patient_data['sex']}")
    
    pdf.ln(2)
    
    # Doctor Block
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 8, "Medical Team:", 0, 1)
    pdf.info_row("Attending Physician:", f"Dr. {doctor_name}")
    pdf.info_row("Examination Date:", datetime.now().strftime("%Y-%m-%d %H:%M"))
    pdf.info_row("Department:", "Cardiology") # Placeholder or passed param
    
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, "Patient History / Notes:", 0, 1)
    pdf.set_font('Arial', '', 10)
    # Use multi_cell for long text
    pdf.multi_cell(0, 6, patient_data.get('medical_history_notes', 'None'))
    pdf.ln(10)
    
    # --- 2. Clinical Metrics ---
    pdf.section_title("Clinical Analysis")
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 10, f"Heart Rate: {int(bpm)} BPM", 1, 0, 'C', 1)
    pdf.cell(95, 10, f"HR Variability: {int(hrv)} ms", 1, 1, 'C', 1)
    pdf.ln(10)
    
    # --- 3. AI Diagnosis ---
    pdf.section_title("AI Risk Assessment")
    
    risk_percent = risk_score * 100
    if risk_score > 0.5:
        status = "HIGH RISK - Myocardial Infarction Detected"
        color = (231, 76, 60) # Red
    else:
        status = "LOW RISK - Normal Sinus Rhythm"
        color = (46, 204, 113) # Green
        
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(*color)
    pdf.cell(0, 10, f"Risk Score: {risk_percent:.1f}%", 0, 1)
    pdf.cell(0, 10, f"Interpretation: {status}", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # --- 4. ECG Visualization ---
    pdf.section_title("ECG Trace (Lead V1)")
    if fig_path and os.path.exists(fig_path):
        # Center image
        pdf.image(fig_path, x=15, w=180)
    pdf.ln(5)
    
    # --- 5. Disclaimer ---
    pdf.set_y(-40)
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, f"DISCLAIMER: This report is generated by MedAI-Cardiac. Validated by Dr. {doctor_name}. It is intended for screening purposes only.")
    
    return pdf.output(dest='S').encode('latin-1')
